name: S3 Deploy for SpringIdle API
on: [push]
env:
  BUCKET_NAME : ${{ secrets.S3_BUCKET }}
  AWS_REGION : ${{ secrets.S3_BUCKET_REGION }}
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build
        run: |
             pip install -r requirements.txt --target ./tmp_package
             cd ./tmp_package
             zip -r9 ../function.zip .
             cd ..
             rm -rf tmp_package/
             zip -g ./function.zip -r app
             zip -g ./function.zip main.py
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/springIdle-API-deploy-s3
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      # Upload a file to AWS s3
      - name:  Deploy
        run: |
          aws s3 cp ./function.zip s3://${{ env.BUCKET_NAME }}/